name: gdh_x
description: "Guided Drug Handling – eXpert"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bluetooth_serial: ^0.4.0
  flutter_local_notifications: ^16.1.0
  permission_handler: ^11.3.1
  flutter_foreground_task: ^6.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
